services:
  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfiles/frontend.Dockerfile
    container_name: escapavelo-frontend 
    env_file:
      - apps/frontend/.env
    networks:
      - private_backend
    depends_on:
      - backend
    expose:
      - "4000"

  backend:
    build:
      context: .
      dockerfile: docker/Dockerfiles/backend.Dockerfile
    container_name: escapavelo-backend
    env_file:
      - apps/backend/.env
    volumes:
      # Format: [chemin_sur_le_vps]:[chemin_dans_le_conteneur]
      - images:/uploads
    networks:
      - private_backend
    depends_on:
      - mariadb
    expose: 
    - "3000"

  mariadb:
    image: mariadb:11.8.5
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - private_backend

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro        # Partage les certificats
      - /var/www/certbot:/var/www/certbot:ro        # Pour la vérification Let's Encrypt
    restart: always
    networks:
      - private_backend
    depends_on:
      - frontend
      - backend
volumes:
  mariadb_data:
  images:

networks:
  private_backend:
    driver: bridge
